Create javascript-style.md
freckle/guides pull request #2
Opened 2016-09-24 00:31 UTC by joris974

Inspired by Airbnb Frontend Javascript Guide. I will complete this list

2016-09-24 00:32 UTC, AKurilin commented
"javascript", heh. Looks good but let's have @cdparks provide sanity here.

2016-09-26 16:29 UTC, cdparks commented on javascript-style.md
> +  { name: "Jeff" }
I thought we were using `{name: "Jeff"}` to correspond with arrays: `[1, 2, 3]` instead of `[ 1, 2, 3 ]`.

2016-09-26 16:30 UTC, cdparks commented on javascript-style.md
> +Each React component should live in its. This rule only apply to stateful component. If you have a component that uses small stateless components specific to the main component you can put them in on
`in its own file` and `to stateful components`.

2016-09-26 16:30 UTC, cdparks commented on javascript-style.md
> +// Here the `Image` component is highly reusable and should be moved in it's own file
`moved to its own file`

2016-09-26 16:31 UTC, cdparks requested changes

2016-09-26 16:31 UTC, cdparks commented
Otherwise, looks good :+1:

2016-09-27 15:39 UTC, cdparks approved these changes

2016-09-27 16:19 UTC, merged