[WIP] Add Frontend Guide
freckle/guides pull request #6
Opened 2017-07-11 21:36 UTC by joris974

This is a WIP. 

I will completed missing sections.
If you think about a missing section please let me know.

2017-07-11 21:41 UTC, jdreaver commented
Awesome!

* Are you going to have an in-depth general JS style guide here, or would that be a separate guide?
* Side question: would you be cool with using Shake to manage the frontend instead of using the scripts directly? That way we won't accidentally diverge between how Shake does things and how your scripts do things. For example, "build all" is just `./build.sh build-frontend`. This includes setup. Also resetting is just `./build.sh clean-frontend` and then a build.

2017-07-12 21:42 UTC, eborden commented
Might want to add @stackptr to this review.

2017-07-12 21:55 UTC, cdparks requested changes
Thanks for working on this, Joris.

2017-07-12 21:55 UTC, cdparks commented on frontend-guide.md
> +  - [Teacher Dashboard](https://classroom.frontrowed.com)
"split into" or "split between"

2017-07-12 21:55 UTC, cdparks commented on frontend-guide.md
> +All applications use the same stack, share the same tools, build processes, guidelines, architecture, and produce the same type of output.
"All applications use the same stack; share the same tools, build processes, guidelines, and architecture; and produce the same type of output"

2017-07-12 21:55 UTC, cdparks commented on frontend-guide.md
> +All interactions should be thought be used by a touch device.
"All interactions should support using a touch device"

2017-07-12 21:55 UTC, cdparks commented on frontend-guide.md
> +Trackpads on ChromeBook is not easy to master and our users have difficulties being precise with it. That's why a lot of ChromeBook users cannot use the drawing features in Math questions.
"Trackpads on Chromebook are not easy to master"

2017-07-12 21:55 UTC, cdparks commented on frontend-guide.md
> +All build steps are written in a bash file at the root of each project call `build.sh`.
"called build.sh"

2017-07-12 21:55 UTC, cdparks commented on frontend-guide.md
> +It contains all the steps to create the different output of each web applications.
"each web application"

2017-07-12 21:55 UTC, cdparks commented on frontend-guide.md
> +- Versionifying CSS bundle
"Versioning"

2017-07-12 21:55 UTC, cdparks commented on frontend-guide.md
> +The build process
WIP?

2017-07-12 21:55 UTC, cdparks commented on frontend-guide.md
> +Each build type (`dev` or `prod`) use a different cache file for this process (`browserify-cache-development.json`).
"uses a different cache file"

2017-07-12 21:55 UTC, cdparks commented on frontend-guide.md
> +When calling an API resource, we use Backbone Collections and Models to transform them into usable, type-checked, javascript usuable class.
"usable", though I would just say objects here probably

2017-07-12 21:55 UTC, cdparks commented on frontend-guide.md
> +Every resource is atomically defined by it's model. Each model contains a `parse` function validating and transforming data from API response.
I'm not sure what "atomically" means here

2017-07-12 21:55 UTC, cdparks commented on frontend-guide.md
> +  // Validating the API response contains the keys we expect and the values are the type we expect
"Validating the API response contains the keys and values we expect _at runtime_"

2017-07-12 21:55 UTC, cdparks commented on frontend-guide.md
> +For each model we define the type of the return of the `get` function for each valid key. Calling `get` on a non valid `key` should throw a flow error, same for using the value as the incorrect type.
"should raise a flow error _at compile time_"

2017-07-12 21:55 UTC, cdparks commented on frontend-guide.md
> +[Flow](https://flow.org/) is a tool that add a layer of typing to javascript code. It relies on annotations in the code to figure out which type are the elements. When running `flow check`, flow will
I would say "It relies on annotations in the code to determine the types of expressions". Flow also does some type inference, but it's really weak, and only improves if you have (usually) function-argument annotations.

2017-07-12 21:55 UTC, cdparks commented on frontend-guide.md
> +Importing an element to a file will also import its type but you can chose to only import its type.
I would say importing "a name into a module imports its type". Or maybe a binding?

2017-07-12 21:55 UTC, cdparks commented on frontend-guide.md
> +By contention the first `describe` should contain the name of the tested file. Every nested `describe` should contain the name of the tested function.
"By convention"

2017-07-12 21:55 UTC, cdparks commented on frontend-guide.md
> +describe("my-nice-helper", function() {
I would point out why we use `function` instead of arrow functions here. If I recall, `mocha` does something sneaky with `this`

2017-07-12 21:57 UTC, eborden reviewed
Looking great! Thanks for putting this together.

2017-07-12 21:57 UTC, eborden commented on frontend-guide.md
> +All applications use the same stack, share the same tools, build processes, guidelines, architecture, and produce the same type of output.
Thank gawd!

2017-07-12 21:57 UTC, eborden commented on frontend-guide.md
> +yarn lint
Might be helpful to add that code climate checks lint errors.

2017-07-13 20:15 UTC, cdparks approved these changes

2017-07-13 20:37 UTC, eborden commented on frontend-guide.md
> +describe("my-nice-helper", function() {
Mmmmm, love me some dynamic binding.

2017-07-13 22:20 UTC, merged